// Generated by extendr: Do not edit by hand
#include <stdio.h>

extern int write__make_{{{mod_name}}}_wrappers(const char *package_name, const char *out_path);

int main(int argc, char **argv) {
    if (argc != 3) {
        fprintf(stderr, "extendr document: expected 2 args (package_name, out_path), got %d\n", argc - 1);
        return 2;
    }
    return write__make_{{{mod_name}}}_wrappers(argv[1], argv[2]);
}