// Generated by extendr: Do not edit by hand
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let wrapper_path = "../R/extendr-wrappers.R";
    let wrappers = {{{lib_name}}}::get_{{{mod_name}}}_metadata()
        .make_r_wrappers(true, "{{{pkg_name}}}")
        .map_err(|e| format!("failed to generate wrappers: {e}"))?;
    std::fs::write(wrapper_path, wrappers)
        .map_err(|e| format!("failed to write {wrapper_path}: {e}"))?;
    Ok(())
}