# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib {{{pkg_name}}}, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @param name A name to greet.
#' @export
hello <- function(name) .Call(wrap__hello, name)

# nolint end
