#' Generate LICENSE.note file.
#'
#' LICENSE.note generated by this function lists dependent Rust packages infomation.
#' To use this function, the `cargo metadata` command must be available.
#' @param force Logical indicating whether to re-generating LICENSE.note if LICENSE.note is already exists.
#' @inheritParams register_extendr
#' @return No return value, called for side effects.
#' @export
write_license_note <- function(path = ".", force = TRUE) {
  if (!cargo_command_available(c("metadata", "--help"))) {
    cli::cli_abort(
      c(
        "The {.code cargo metadata} command is required to run the {.fun write_license_note} function.",
        "Please setup cargo first."
      ),
      class = "rextendr_error"
    )
  }

  manifest_file <- rprojroot::find_package_root_file("src", "rust", "Cargo.toml", path = path)
  out_file <- rprojroot::find_package_root_file("LICENSE.note", path = path)

  if (!isTRUE(force) && file.exists(out_file)) {
    cli::cli_abort(
      c(
        "LICENSE.note already exists.",
        "If you want to re-generate LICENSE.note, set `force = TRUE` to {.fun write_license_note}."
      ),
      class = "rextendr_error"
    )
  }

  cargo_metadata_common_args <- c(
    "--format-version", "1",
    "--manifest-path", manifest_file
  )

  package_names <- processx::run(
    "cargo",
    c(
      "metadata",
      cargo_metadata_common_args,
      "--no-deps"
    )
  )$stdout %>%
    jsonlite::parse_json() %>%
    purrr::pluck("packages") %>%
    purrr::map_chr("name")

  list_license <- processx::run(
    "cargo",
    c(
      "metadata",
      cargo_metadata_common_args
    )
  )$stdout %>%
    jsonlite::parse_json() %>%
    purrr::pluck("packages")

  .prep_authors <- function(authors, package) {
    ifelse(!rlang::is_empty(authors), authors, paste0(package, " authors")) %>%
      stringi::stri_replace_all("", regex = r"(\ <.+?>)")
  }

  separator <- "-------------------------------------------------------------"

  note_header <- paste0(
    "The binary compiled from the source code of this package contains the following Rust packages.\n",
    "\n",
    "\n",
    separator
  )

  package_name <- RcppTOML::parseTOML(manifest_file)$package$name

  note_body <- list_license %>%
    purrr::keep(function(x) !(x$name %in% package_names)) %>%
    purrr::map_chr(
      function(x) {
        paste0(
          "\n",
          "Name:        ", x$name, "\n",
          "Repository:  ", x$repository, "\n",
          "Authors:     ", .prep_authors(paste0(unlist(x$authors), collapse = ", "), x$name), "\n",
          "License:     ", x$license, "\n",
          "\n",
          separator
        )
      }
    )

  c(note_header, note_body) %>%
    writeLines(out_file)
}
