#' Generate LICENSE.note file.
#'
#' LICENSE.note generated by this function contains information about Rust crate
#' dependencies. To use this function, the
#' [cargo-license](https://crates.io/crates/cargo-license) command must be
#' installed.
#'
#' @param path character scalar, the R package directory
#' @param echo logical scalar, whether to print cargo command and outputs to the
#' console (default is `TRUE`)
#' @param quiet logical scalar, whether to signal successful writing of
#' LICENSE.note (default is `FALSE`)
#' @param force logical scalar, whether to regenerate LICENSE.note if
#' LICENSE.note already exists (default is `TRUE`)
#'
#' @return No return value, called for side effects.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' write_license_note()
#' }
write_license_note <- function(
    path = ".",
    echo = TRUE,
    quiet = FALSE,
    force = TRUE) {
  check_string(path, class = "rextendr_error")
  check_bool(echo, class = "rextendr_error")
  check_bool(force, class = "rextendr_error")

  if (!cargo_command_available(c("license", "--help"))) {
    cli::cli_abort(
      c(
        "The {.code cargo license} command is required \\
        to run the {.fun write_license_note} function.",
        "*" = "Please install cargo-license \\
        ({.url https://crates.io/crates/cargo-license}) first.",
        i = "Run {.code cargo install cargo-license} from your terminal."
      ),
      class = "rextendr_error"
    )
  }

  rust_folder <- rprojroot::find_package_root_file(
    "src", "rust",
    path = path
  )

  manifest_path <- normalizePath(
    file.path(rust_folder, "Cargo.toml"),
    winslash = "/",
    mustWork = FALSE
  )

  outfile <- rprojroot::find_package_root_file(
    "LICENSE.note",
    path = path
  )

  if (isFALSE(force) && file.exists(outfile)) {
    cli::cli_abort(
      c(
        "LICENSE.note already exists.",
        "If you want to regenerate LICENSE.note, \\
        set `force = TRUE` to {.fun write_license_note}."
      ),
      class = "rextendr_error"
    )
  }

  args <- c(
    "license",
    "--authors",
    "--json",
    "--avoid-build-deps",
    "--avoid-dev-deps",
    "--manifest-path", manifest_path
  )

  out <- processx::run(
    command = "cargo",
    args = args,
    error_on_status = TRUE,
    wd = rust_folder,
    echo_cmd = echo,
    echo = echo,
    env = get_cargo_envvars()
  )

  licenses <- jsonlite::parse_json(
    out[["stdout"]],
    simplifyDataFrame = TRUE
  )

  metadata <- read_cargo_metadata(path = path)

  package_names <- metadata[["packages"]][["dependencies"]][[1]][["name"]]

  licenses <- licenses[licenses[["name"]] %in% package_names, ]

  .prep_authors <- function(authors, package) {
    authors <- ifelse(
      is.na(authors),
      paste0(package, " authors"),
      authors
    )

    authors <- stringi::stri_replace_all_regex(authors, r"(\ <.+?>)", "")

    stringi::stri_replace_all_regex(authors, r"(\|)", ", ")
  }

  separator <- "-------------------------------------------------------------"

  note_header <- glue::glue(
    "
    The binary compiled from the source code of this package \\
    contains the following Rust crates:


    {separator}
    "
  )

  note_body <- glue::glue_data(
    licenses,
    "

    Name:        {name}
    Repository:  {repository}
    Authors:     {.prep_authors(authors, name)}
    License:     {license}

    {separator}
    "
  )

  write_file(
    text = c(note_header, note_body),
    path = outfile,
    search_root_from = path,
    quiet = quiet
  )
}
